apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: linux-network-map
  namespace: tuto
  labels:
    app: linux-network-map
spec:
  ingressClassName: kakao
  defaultBackend:
    service:
      name: linux-network-map
      port:
        number: 80
  rules:
  - host: netuto.dev.onkakao.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: linux-network-map
            port:
              number: 80
  tls:
  - hosts:
    - netuto.dev.onkakao.net
    # secretName: linux-network-map
