apiVersion: v1
kind: Service
metadata:
  name: linux-network-map
  namespace: tuto
  labels:
    app: linux-network-map
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: linux-network-map
  sessionAffinity: None
